Unattended execution

diff --git a/x/x b/x/x
--- a/x/x
+++ b/x/x
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-VERSION=1.0.6
+VERSION=1.0.7
 # Name: x
 # Description: OpenAI API for bash: Translate a command in natural language into a bash one-liner.
 #              Become a linux guru in no time! (or at least a little bit better)
@@ -29,20 +29,21 @@ if [ -z "$OPENAI_API_KEY" ]; then
     exit 1
 fi
 
+export prompt="Translate this into a Bash one-liner"
+export model="text-davinci-002"
+export temperature=0.7
+export max_tokens=60
+
+export tmp_output_file=$(mktemp /tmp/x.XXXXXX)
+export x_history_file=~/.x
+
 ###################################################################################
 ## Main ##
-main() {
+x_main() {
     # Version 1.0.5
-    # Usage: main "$@"
+    # Usage: x_main "$@"
     # Description: Main function
 
-    local model="text-davinci-002"
-    local temperature=0.7
-    local max_tokens=60
-
-    local tmp_output_file=$(mktemp /tmp/x.XXXXXX)
-
-    local x_history_file=~/.x
     touch $x_history_file 2> /dev/null
 
     # get the options
@@ -51,47 +52,20 @@ main() {
     local question=$@
     while [ -z "$question" ]; do read -p "What do you want to do? " question;done
 
-    local prompt="Translate this into a Bash one-liner: $question"
-
-    # make sure the question ends with a dot
-    [[ $question != *"."$ ]] && prompt="$prompt."
-
-    curl -q -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $OPENAI_API_KEY" \
-        -d '{"model": "'$model'", "prompt": "'"$prompt"'", "temperature": '$temperature', "max_tokens": '$max_tokens'}' \
-        -o $tmp_output_file https://api.openai.com/v1/completions > /dev/null 2>&1
-
-    # add the command to the x history
-    cat $tmp_output_file >> $x_history_file
-
-    local command=$(cat $tmp_output_file | jq -r '.choices[0].text')
+    local request="$prompt: $question"
+    local command="$(x_query_openai "$request")"
 
     # show the command
     echo -e "\e[1;37m"${command}"\e[0m"
-
-    # clean up the $command to make sure it's safe to execute
-    command=$(echo "$command" | sed 's/"/\"/g'|sed "s/'/\'/"|tr -d '\n')
 
     read -p "[E]xecute or [r]etry? [e/r/N] " -n 1 -r
     echo
     case $REPLY in
         e)
-            # excute the command in a new shell
-            bash -c "$command"
-
-            # if the command was successful, add it to the history
-            # if there are timestamps in the history, add one before the command
-
-            if [ $? -eq 0 ]; then
-               if grep -q "^#" ~/.bash_history; then
-                   echo -e "#$(date +%s)\n${command}" >> ~/.bash_history
-               else
-                   echo "${command}" >> ~/.bash_history
-               fi
-            fi
-
+            x_execute_command "$command"
             ;;
         r)  echo "Retrying..."
-            main "$@"
+            x_main "$@"
             ;;
         *)  echo "Aborting..."
             ;;
@@ -103,7 +77,7 @@ main() {
 }
 
 x_get_opts() {
-    # Version 1.0.5
+    # Version 1.0.7
     # Usage: x_get_opts "$@"
     # Description: Get the options
 
@@ -127,6 +101,14 @@ x_get_opts() {
                 ;;
             -d|--display)
                 x_show_history
+                exit 0
+                ;;
+            -e|--execute)
+                shift
+                local request="$prompt: $@"
+                local command="$(x_query_openai "$request")"
+                echo -e "\e[1;37m"${command}"\e[0m"
+                x_execute_command "$command"
                 exit 0
                 ;;
             -f|--find|--search)
@@ -155,11 +137,29 @@ x_get_opts() {
         shift
     done
 }
+###################################################################################
 
-# x_execute_command() {
+x_execute_command() {
+    # Version 1.0.7
+    # Usage: x_execute_command <command>
+    # Description: Execute the command
 
-# }
+    local command=$@
 
+    # excute the command in a new shell
+    bash -c "$command"
+
+    # if the command was successful, add it to the history
+    # if there are timestamps in the history, add one before the command
+
+    if [ $? -eq 0 ]; then
+        if grep -q "^#" ~/.bash_history; then
+            echo -e "#$(date +%s)\n${command}" >> ~/.bash_history
+        else
+            echo "${command}" >> ~/.bash_history
+        fi
+    fi
+}
 
 x_help() {
     # Version 1.0.5
@@ -169,7 +169,7 @@ x_help() {
     echo "Usage: x <command>"
     echo "Example: x create a ssh key pair named test13 in /tmp with no password"
     echo "         x find the files over 1go in /home. use sudo"
-    echo "         x zip all the files in /tmp older than 1 day and send it by email to you@domain.com"
+    echo "         x zip all the files in /tmp older than 1 day and send it by email to you@dox_main.com"
     echo
     echo "Options:"
     echo "  -h, --help      Show this help message and exit"
@@ -189,79 +189,6 @@ x_clear_history() {
 
     local x_history_file=~/.x
     echo -n "" > $x_history_file
-}
-
-x_show_history() {
-    # Version 1.0.5
-    # Usage: x_show_history
-    # Description: Show the x history
-
-    local x_history_file=~/.x
-    cat $x_history_file
-}
-
-x_show_version() {
-    # Version 1.0.5
-    # Usage: x_show_version
-    # Description: Show the version of x
-
-    echo $VERSION
-}
-
-x_search_history() {
-    # Version 1.0.5
-    # Usage: x_search_history <search term>
-    # Description: Search the x history
-
-    local x_history_file=~/.x
-    local search_term=$1
-    shift
-    local search_options=$@
-
-    grep -i "$search_term" $x_history_file $search_options|jq -r '.choices[0].text'|sort -r |uniq
-}
-
-x_show_total_token() {
-    # Version 1.0.5
-    # Usage: x_show_total_token
-    # Description: Show the total number of tokens used in the x history
-
-    local total_tokens=$(x_get_tokens_stats|jq '.total_tokens'|tr -d '"')
-    local total_requests=$(x_get_tokens_stats|jq '.total_requests'|tr -d '"')
-    echo "$total_tokens tokens in $total_requests requests"
-}
-
-x_show_token_usage() {
-    # Version 1.0.5
-    # Usage: x_show_token_usage
-    # Description: Show the token stats (total, average, min, max) for the x history
-
-    local stats=$(x_get_tokens_stats)
-
-    echo -e "\e[1;37mTotal requests\e[0m: $(echo $stats|jq '.total_requests'|tr -d '"')"
-    echo -e "\e[4;1;34mPrompt\e[0m:"
-    echo -e "\e[1;37mTotal tokens\e[0m: $(echo $stats|jq '.prompt.total_tokens'|tr -d '"')"
-    echo -e "\e[1;37mAverage tokens\e[0m: $(echo $stats|jq '.prompt.average_tokens'|tr -d '"')"
-    echo -e "\e[1;37mMinimun tokens\e[0m: $(echo $stats|jq '.prompt.min_tokens'|tr -d '"')"
-    echo -e "\e[1;37mMaximun tokens\e[0m: $(echo $stats|jq '.prompt.max_tokens'|tr -d '"')"
-    echo -e "\e[4;1;34mCompletion\e[0m:"
-    echo -e "\e[1;37mTotal tokens\e[0m: $(echo $stats|jq '.completion.total_tokens'|tr -d '"')"
-    echo -e "\e[1;37mAverage tokens\e[0m: $(echo $stats|jq '.completion.average_tokens'|tr -d '"')"
-    echo -e "\e[1;37mMinimun tokens\e[0m: $(echo $stats|jq '.completion.min_tokens'|tr -d '"')"
-    echo -e "\e[1;37mMaximun tokens\e[0m: $(echo $stats|jq '.completion.max_tokens'|tr -d '"')"
-    echo -e "\e[4;1;34mTotal\e[0m:"
-    echo -e "\e[1;37mTotal tokens used\e[0m: $(echo $stats|jq '.total.total_tokens'|tr -d '"')"
-    echo -e "\e[1;37mAverage tokens\e[0m: $(echo $stats|jq '.total.average_tokens'|tr -d '"')"
-    echo -e "\e[1;37mMinimun tokens\e[0m: $(echo $stats|jq '.total.min_tokens'|tr -d '"')"
-    echo -e "\e[1;37mMaximun tokens\e[0m: $(echo $stats|jq '.total.max_tokens'|tr -d '"')"
-}
-
-x_show_raw_stats() {
-    # Version 1.0.5
-    # Usage: x_show_raw_stats
-    # Description: Show the raw stats for the x history
-
-    x_get_tokens_stats
 }
 
 x_get_tokens_stats() {
@@ -380,5 +307,128 @@ x_get_tokens_stats() {
     echo $stats
 }
 
+x_search_history() {
+    # Version 1.0.5
+    # Usage: x_search_history <search term>
+    # Description: Search the x history
+
+    local x_history_file=~/.x
+    local search_term=$1
+    shift
+    local search_options=$@
+
+    grep -i "$search_term" $x_history_file $search_options|jq -r '.choices[0].text'|sort -r |uniq
+}
+
+x_show_history() {
+    # Version 1.0.5
+    # Usage: x_show_history
+    # Description: Show the x history
+
+    local x_history_file=~/.x
+    cat $x_history_file
+}
+
+x_show_token_usage() {
+    # Version 1.0.5
+    # Usage: x_show_token_usage
+    # Description: Show the token stats (total, average, min, max) for the x history
+
+    local stats=$(x_get_tokens_stats)
+
+    echo -e "\e[1;37mTotal requests\e[0m: $(echo $stats|jq '.total_requests'|tr -d '"')"
+    echo -e "\e[4;1;34mPrompt\e[0m:"
+    echo -e "\e[1;37mTotal tokens\e[0m: $(echo $stats|jq '.prompt.total_tokens'|tr -d '"')"
+    echo -e "\e[1;37mAverage tokens\e[0m: $(echo $stats|jq '.prompt.average_tokens'|tr -d '"')"
+    echo -e "\e[1;37mMinimun tokens\e[0m: $(echo $stats|jq '.prompt.min_tokens'|tr -d '"')"
+    echo -e "\e[1;37mMaximun tokens\e[0m: $(echo $stats|jq '.prompt.max_tokens'|tr -d '"')"
+    echo -e "\e[4;1;34mCompletion\e[0m:"
+    echo -e "\e[1;37mTotal tokens\e[0m: $(echo $stats|jq '.completion.total_tokens'|tr -d '"')"
+    echo -e "\e[1;37mAverage tokens\e[0m: $(echo $stats|jq '.completion.average_tokens'|tr -d '"')"
+    echo -e "\e[1;37mMinimun tokens\e[0m: $(echo $stats|jq '.completion.min_tokens'|tr -d '"')"
+    echo -e "\e[1;37mMaximun tokens\e[0m: $(echo $stats|jq '.completion.max_tokens'|tr -d '"')"
+    echo -e "\e[4;1;34mTotal\e[0m:"
+    echo -e "\e[1;37mTotal tokens used\e[0m: $(echo $stats|jq '.total.total_tokens'|tr -d '"')"
+    echo -e "\e[1;37mAverage tokens\e[0m: $(echo $stats|jq '.total.average_tokens'|tr -d '"')"
+    echo -e "\e[1;37mMinimun tokens\e[0m: $(echo $stats|jq '.total.min_tokens'|tr -d '"')"
+    echo -e "\e[1;37mMaximun tokens\e[0m: $(echo $stats|jq '.total.max_tokens'|tr -d '"')"
+}
+
+x_show_total_token() {
+    # Version 1.0.5
+    # Usage: x_show_total_token
+    # Description: Show the total number of tokens used in the x history
+
+    local total_tokens=$(x_get_tokens_stats|jq '.total_tokens'|tr -d '"')
+    local total_requests=$(x_get_tokens_stats|jq '.total_requests'|tr -d '"')
+    echo "$total_tokens tokens in $total_requests requests"
+}
+
+x_show_raw_stats() {
+    # Version 1.0.5
+    # Usage: x_show_raw_stats
+    # Description: Show the raw stats for the x history
+
+    x_get_tokens_stats
+}
+
+x_show_token_usage() {
+    # Version 1.0.5
+    # Usage: x_show_token_usage
+    # Description: Show the token stats (total, average, min, max) for the x history
+
+    local stats=$(x_get_tokens_stats)
+
+    echo -e "\e[1;37mTotal requests\e[0m: $(echo $stats|jq '.total_requests'|tr -d '"')"
+    echo -e "\e[4;1;34mPrompt\e[0m:"
+    echo -e "\e[1;37mTotal tokens\e[0m: $(echo $stats|jq '.prompt.total_tokens'|tr -d '"')"
+    echo -e "\e[1;37mAverage tokens\e[0m: $(echo $stats|jq '.prompt.average_tokens'|tr -d '"')"
+    echo -e "\e[1;37mMinimun tokens\e[0m: $(echo $stats|jq '.prompt.min_tokens'|tr -d '"')"
+    echo -e "\e[1;37mMaximun tokens\e[0m: $(echo $stats|jq '.prompt.max_tokens'|tr -d '"')"
+    echo -e "\e[4;1;34mCompletion\e[0m:"
+    echo -e "\e[1;37mTotal tokens\e[0m: $(echo $stats|jq '.completion.total_tokens'|tr -d '"')"
+    echo -e "\e[1;37mAverage tokens\e[0m: $(echo $stats|jq '.completion.average_tokens'|tr -d '"')"
+    echo -e "\e[1;37mMinimun tokens\e[0m: $(echo $stats|jq '.completion.min_tokens'|tr -d '"')"
+    echo -e "\e[1;37mMaximun tokens\e[0m: $(echo $stats|jq '.completion.max_tokens'|tr -d '"')"
+    echo -e "\e[4;1;34mTotal\e[0m:"
+    echo -e "\e[1;37mTotal tokens used\e[0m: $(echo $stats|jq '.total.total_tokens'|tr -d '"')"
+    echo -e "\e[1;37mAverage tokens\e[0m: $(echo $stats|jq '.total.average_tokens'|tr -d '"')"
+    echo -e "\e[1;37mMinimun tokens\e[0m: $(echo $stats|jq '.total.min_tokens'|tr -d '"')"
+    echo -e "\e[1;37mMaximun tokens\e[0m: $(echo $stats|jq '.total.max_tokens'|tr -d '"')"
+}
+
+x_show_version() {
+    # Version 1.0.5
+    # Usage: x_show_version
+    # Description: Show the version of x
+
+    echo $VERSION
+}
+
+x_query_openai() {
+    # Version 1.0.7
+    # Usage: x_query_openai <query>
+    # Description: Query the OpenAI API
+
+    local query=$@
+
+    # make sure the question ends with a dot
+    [[ $query != *"."$ ]] && request="$request."
+
+    curl -q -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $OPENAI_API_KEY" \
+        -d '{"model": "'$model'", "prompt": "'"$request"'", "temperature": '$temperature', "max_tokens": '$max_tokens'}' \
+        -o $tmp_output_file https://api.openai.com/v1/completions > /dev/null 2>&1
+
+    # add the command to the x history
+    cat $tmp_output_file >> $x_history_file
+
+    local command=$(cat $tmp_output_file | jq -r '.choices[0].text')
+
+    # clean up the $command to make sure it's safe to execute
+    command=$(echo "$command" | sed 's/"/\"/g'|sed "s/'/\'/"|tr -d '\n')
+
+    echo "$command"
+}
+
 ############################################################################################################
-main "$@"
+x_main "$@"
